Dockerfile

diff --git a/controller/Dockerfile b/controller/Dockerfile
--- a/controller/Dockerfile
+++ b/controller/Dockerfile
@@ -25,8 +25,8 @@ FROM golang AS eBPFRetinaStage
 WORKDIR /tmp
 RUN tdnf install -y unzip && \
     curl -L -o eBPFRetina.zip https://www.nuget.org/api/v2/package/Microsoft.Wcn.Observability.eBPF.Retina.x64/0.1.0-prerelease.3 && \
-    mkdir eBPFRetina && \
-    unzip -d eBPFRetina eBPFRetina.zip || true
+    unzip -d eBPFRetina eBPFRetina.zip && \
+    if [ ! -d "eBPFRetina" ]; then echo "eBPFRetina directory not found after unzip!" && exit 1; fi
 
 FROM golang AS intermediate
 ARG APP_INSIGHTS_ID # set to enable AI telemetry
